- name: Install Nginx web server
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Replace default Nginx config
  ansible.builtin.copy:
    src: /ica0002/roles/nginx/files/default
    dest: /etc/uwsgi/apps-enabled/agama.ini
    mode: '0644'
  notify:
    - Restart nginx

- name: Ensure Nginx service is started and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

