- name: Install Nginx web server
  ansible.builtin.apt:
    name: 
      - nginx
      - prometheus-nginx-exporter
    state: present

# Create the Prometheus Nginx config file in sites-available
- name: Prometheus Nginx config
  ansible.builtin.template:
    src: prometheus_config.j2
    dest: /etc/nginx/sites-available/prometheus
    mode: '0644'
    force: yes
  notify:
    - Restart nginx prometheus


# Default Nginx config
- name: default Nginx config
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
    mode: '0644'
    force: yes
  notify: 
    - Restart nginx

# Ensure Nginx and Prometheus services are started and enabled
- name: Ensure Nginx and Prometheus services are started and enabled
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - nginx
    - prometheus-nginx-exporter