- name: Install Nginx web server
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Replace default Nginx config
  ansible.builtin.copy:
    src: default
    dest: /etc/nginx/sites-enabled/default
    mode: '0644'
  notify: Restart nginx

- name: Ensure Nginx service is started and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
