- name: Install Nginx web server
  ansible.builtin.apt:
    name: 
      - nginx
      - prometheus-nginx-exporter
    state: present

- name: default Nginx config
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
    mode: '0644'
    force: yes
  notify: 
    - Restart nginx

- name: Ensure Nginx and Prometheus services are started and enabled
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - nginx
    - prometheus-nginx-exporter