- name: Install Haproxy
  ansible.builtin.apt:
    name: haproxy
    state: present

- name: Haproxy Config
  ansible.builtin.template:
    src: haproxy.cnf.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  notify: Restart Haproxy

- name: Install Haproxy Exporter
  ansible.builtin.apt:
    name: prometheus-haproxy-exporter
    state: present

- name: Haproxy Exporter config
  ansible.builtin.template:
    src: haproxy_exporter.j2
    dest: /etc/default/prometheus-haproxy-exporter
    mode: '0644'
  notify: Restart Haproxy Exporter

- name: Assign cnames
  include_role:
    name: "cname"
  vars:
    service: "lb{{inventory_hostname | replace('davidayson8','')}}"