- name: Install InfluxDB
  ansible.builtin.apt:
    name: influxdb
    state: present
    update_cache: yes

- name: Ensure InfluxDB is started and enabled
  ansible.builtin.service:
    name: influxdb
    state: started
    enabled: true

- name: Make dir for apt key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  
- name: Install Telegraf Repo Key
  ansible.builtin.get_url:
    url:  https://repos.influxdata.com/influxdata-archive.key
    dest: /etc/apt/keyrings/telegraf.asc
    mode: '0644'

- name: Add Telegraf Repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/telegraf.asc] https://repos.influxdata.com/debian stable main"
    state: present
    update_cache: true

- name: Install Telegraf
  ansible.builtin.apt:
    name: telegraf=1.28.2-1
    state: present

- name: Run Telegraf template
  ansible.builtin.template:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf
    mode: '0644'
  
- name: Make sure Telegraf is enabled and running
  ansible.builtin.service:
    name: telegraf
    state: started
    enabled: true
  notify: Restart Telegraf

- name: Install InfluxDB stat exporter from git
  ansible.builtin.get_url:
    url: https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_amd64
    dest: /usr/local/bin/
    mode: '0500'
    owner: prometheus
  notify: Restart Systemctl

- name: Import Influxdb Stat Expo Template
  ansible.builtin.template:
    src: influx_stat_expo.service
    dest: /etc/systemd/system/prometheus-influxdb-stats-exporter.service
    mode: '0644'

- name: Import Influxdb Conf Template
  ansible.builtin.template:
    src: influxdb.conf
    dest: /etc/influxdb/influxdb.conf
    mode: '0644'
  notify: Restart InfluxDB

- name: Make sure stats exporter is enabled and running
  ansible.builtin.service:
    name: prometheus-influxdb-stats-exporter
    state: started
    enabled: true
  notify: Restart Systemctl


