- name: Create Grafana directories
  ansible.builtin.file:
    name: /opt/grafana/provisioning/{{ item }}
    state: directory
  loop:
    - dashboards
    - datasources
    mode: '0755'

- name: Copy main.json
  ansible.builtin.copy:
    src: main.json
    dest: /opt/grafana/provisioning/dashboards/main.json
    mode: '0644'

- name: Copy backups.json
  ansible.builtin.copy:
    src: backups.json
    dest: /opt/grafana/provisioning/dashboards/backups.json
    mode: '0644'
    
- name: Copy syslog.json
  ansible.builtin.copy:
    src: syslog.json
    dest: /opt/grafana/provisioning/dashboards/syslog.json
    mode: '0644'
  
- name: Copy mysql.json
  ansible.builtin.copy:
    src: mysql.json
    dest: /opt/grafana/provisioning/dashboards/mysql.json
    mode: '0644'
  
- name: Dashboards template
  ansible.builtin.template:
    src: dashboards.j2
    dest: /opt/grafana/provisioning/dashboards/dashboards.json
    mode: '0644'
  
  - name: Datasources template
  ansible.builtin.template:
    src: dashboards.j2
    dest: /opt/grafana/provisioning/datasources/datasources.json
    mode: '0644'

- name: Create Grafana data container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana
    volumes: /opt/grafana:/etc/grafana
    state: started
    restart_policy: always
    published_ports: "{{ grafana_port }}:3000"
  notify: Restart container