- name: Create Grafana directories
  ansible.builtin.file:
    path: /opt/grafana/provisioning/{{ item }}
    state: directory
    mode: '0755'
  loop:
    - dashboards
    - datasources

- name: Copy main.json
  ansible.builtin.copy:
    src: main.json
    dest: /opt/grafana/provisioning/dashboards/
    mode: '0644'

- name: Copy backups.json
  ansible.builtin.copy:
    src: backups.json
    dest: /opt/grafana/provisioning/dashboards/
    mode: '0644'
    
- name: Copy syslog.json
  ansible.builtin.copy:
    src: syslog.json
    dest: /opt/grafana/provisioning/dashboards/
    mode: '0644'
  
- name: Copy mysql.json
  ansible.builtin.copy:
    src: mysql.json
    dest: /opt/grafana/provisioning/dashboards/
    mode: '0644'
  
- name: Dashboards template
  ansible.builtin.template:
    src: dashboards.yaml
    dest: /opt/grafana/provisioning/dashboards/default.yaml
    mode: '0644'
  
- name: Datasources template
  ansible.builtin.template:
    src: dashboards.yaml
    dest: /opt/grafana/provisioning/datasources/default.yaml
    mode: '0644'

- name: Grafana Template
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
  no_log: true

- name: Create Grafana data container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana
    volumes: /opt/grafana:/etc/grafana
    state: started
    restart_policy: always
    published_ports: "{{ grafana_port }}:3000"
  #notify: Restart container

- name: Assign cnames
  include_role:
    name: "cname"
  vars:
    service: "grafana"