---
- name: Install uWSGI packages
  ansible.builtin.apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3
    state: present

- name: Ensure uWSGI apps-enabled directory exists
  ansible.builtin.file:
    path: /etc/uwsgi/apps-enabled
    state: directory

- name: Configure host uwsgi for AGAMA
  ansible.builtin.template:
    src: agama.ini.j2
    dest: /etc/uwsgi/apps-enabled/agama.ini
    mode: '0600'
    owner: agama
  notify: Restart uwsgi

- name: Ensure the uWSGI service is started
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: true

