---
- name: Install uWSGI packages
  ansible.builtin.apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3
    state: present

- name: Ensure uWSGI apps-enabled directory exists
  ansible.builtin.file:
    path: /etc/uwsgi/apps-enabled
    state: directory

- name: Configure host uwsgi for AGAMA
  ansible.builtin.copy:
    dest: /etc/uwsgi/apps-enabled/agama.ini
    content: |
      [uswgi]
      chdir = /opt/agama
      module = agama:aoo
      env = AGAMA_DATABASE_URI=sqlite:////opt/agama/db.sqlite3
      plugins = python 3
      socket = 127.0.0.1:5000
      uid = agama
    owner: agama
    notify: 
      - Restart uWSGI


- name: Ensure the uWSGI service is started
  service:
    name: uwsgi
    state: started
    enabled: true
