---
- name: Initial setup
  hosts: all
  become: true
  roles:
    - init

- name: host DNS servers
  hosts: dns_servers
  roles:
    - bind

- name: Setup custom DNS
  hosts: resolv
  roles:
    - resolver

- name: Install Prometheus
  hosts: prometheus
  roles: 
    - prometheus
    - nginx

- name: Database server setup
  hosts: db_servers
  become: true
  roles:
    - mysql

- name: Web server setup
  hosts: web_servers
  become: true
  roles:
    - agama
    - uwsgi
    - nginx
