---
- name: Initial setup
  hosts: all
  roles:
    - init

- name: host DNS servers
  hosts: dns_servers
  roles:
    - bind

- name: Setup custom DNS
  hosts: resolv
  roles:
    - resolver

- name: Install Prometheus
  hosts: prometheus
  roles: 
    - prometheus
    - nginx

- name: Install Grafana
  hosts: grafana
  roles: 
    - grafana
    
- name: Database server setup
  hosts: db_servers
  roles:
    - mysql

- name: InfluxDB
  hosts: influx
  roles:
    - influxdb

- name: Web server setup
  hosts: web_servers
  roles:
    - agama
    - uwsgi
    - nginx

- name: Agama Client 
  hosts: agama_client
  roles: 
    - agama_client