- name: Initial setup
  hosts: all
  roles:
    - init

- name: host DNS servers
  hosts: dns_servers
  roles:
    - bind

- name: Setup custom DNS
  hosts: resolv
  roles:
    - resolver

- name: Install Prometheus
  hosts: prometheus
  roles: 
    - prometheus

- name: Install Grafana
  hosts: grafana
  roles: 
    - grafana
    
- name: Database server setup
  hosts: db_servers
  roles:
    - mysql

- name: InfluxDB
  hosts: influxdb
  roles:
    - influxdb

- name: Agama setup
  hosts: agama
  roles:
    - agama
    - uwsgi

- name: Agama-Client setup
  hosts: agama_client
  roles:
    - agama_client

- name: Web server setup
  hosts: web_servers
  roles:
    - nginx


