---
- name: Initial setup
  hosts: all
  become: true
  roles:
    - init

- name: Database server setup
  hosts: db_servers
  become: true
  roles:
    - mysql

- name: Web server setup
  hosts: web_servers
  become: true
  roles:
    - agama
    - uwsgi
    - nginx
