- name: Initial setup
  hosts: all
  roles:
    - init
  tags: init

- name: host DNS servers
  hosts: dns_servers
  roles:
    - bind
  tags: bind

- name: Setup custom DNS
  hosts: resolv
  roles:
    - resolver
  tags: resolver

- name: Install Prometheus
  hosts: prometheus
  roles: 
    - prometheus
  tags: prometheus

- name: Keepalived setup
  hosts: keepalived
  roles:
    - keepalived
  tags: keepalived

- name: Haproxy Setup 
  hosts: haproxy
  roles:
    - haproxy
  tags: haproxy

- name: Docker Setup
  hosts: docker
  roles:
    - docker
  tags: docker

- name: Install Grafana
  hosts: grafana
  roles: 
    - grafana
  tags: grafana

- name: Database server setup
  hosts: db_servers
  roles:
    - mysql
  tags: mysql

- name: InfluxDB
  hosts: influxdb
  roles:
    - influxdb
  tags: influxdb

- name: Agama setup
  hosts: agama
  roles:
    - agama
  tags: agama

- name: Web server setup
  hosts: web_servers
  roles:
    - nginx
  tags: nginx

- name: Agama-Client setup
  hosts: agama_client
  roles:
    - agama_client
  tags: client


