{
 "title": "Backups",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "MySQL Full Backups",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backups_total{user=\"davidayson8\", service=\"mysql\", type=\"full\"}\r\n",
     "legendFormat": "{{instance}} - {{service}} - {{type}} - {{user}}"
    }
   ]
  },
  {
   "title": "InfluxDB Full Backups",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backups_total{user=\"davidayson8\", service=\"influxdb\", type=\"full\"}\r\n",
     "legendFormat": "{{instance}} - {{service}} - {{type}} - {{user}}"
    }
   ]
  },
  {
   "title": "MySQL Backup Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - backup_last_success_time{user=\"davidayson8\",service=\"mysql\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InfluxDB Backup Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - backup_last_success_time{user=\"davidayson8\",service=\"influxdb\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}