{
 "title": "Main",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_Buffers_bytes + node_memory_Cached_bytes + node_memory_MemFree_bytes) / node_memory_MemTotal_bytes ) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "InlfluxDB Stat Exporter",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InfluxDB Write Rate",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 6 },
   "targets": [
    {
     "expr": "rate(influxdb_write_write_ok[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Item Counts for All Discovered Agamas",
   "type": "stat",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"items\") FROM \"autogen\".\"agama-stats\" WHERE $timeFilter GROUP BY time(1m) fill(null)\n"
    }
   ]
  },
  {
   "title": "Bind9 Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Bind9 Request Per Min",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 12 },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total{type=\"A\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {}
   ]
  },
  {
   "title": "Agama Items",
   "type": "stat",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT distinct(\"items\") FROM \"agama-stats\" WHERE $timeFilter GROUP BY \"name::'davidayson8-1.agamadb'\""
    }
   ]
  },
  {
   "title": "MySQL Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MySQL Request Per Min",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 18 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nginx Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nginx Request Per Min",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 24 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Keepalived Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "keepalived_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Keepalived VRRP State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "keepalived_vrrp_state", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Haproxy Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Haproxy Containers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_server_up", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}