- name: Reload Bind9
  ansible.builtin.service:
    name: bind9
    state: reloaded

- name: Restart Bind9
  ansible.builtin.service:
    name: bind9
    state: restarted

- name: Restart Exporter
  ansible.builtin.service:
    name: prometheus-bind-exporter
    state: restarted