- name: Reload Bind9
  ansible.builtin.service:
    name: bind9
    state: reloaded

- name: Restart Bind9
  ansible.builtin.service:
    name: bind9
    state: restarted

- name: Restart Exporter
  ansible.builtin.systemd:
    name: prometheus-bind-exporter
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  