---
- name: Create agama user
  ansible.builtin.user:
    name: agama
    state: present
    shell: /bin/bash
    create_home: yes

- name: Create /opt/agama directory
  ansible.builtin.file:
    state: directory
    path: /opt/agama
    owner: agama

- name: Install agama dependencies
  ansible.builtin.apt:
    name:
      - python3 
      - python3-venv
      - sqlite3
      - python3-flask
      - python3-flask-sqlalchemy
      - python3-jinja2
      - python3-pymysql
    state: present

- name: Install agama application
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama/agama.py
  
