- name: Make Agama Directory 
  ansible.builtin.file:
    path: /opt/agama
    state: directory

- name: Install agama application
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama/agama.py
    mode: '0755'
  
- name: Download docker agama
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
    dest: /opt/agama/Dockerfile
    mode: '0755'

- name: Build Docker Image
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama

- name: Create a data container
  community.docker.docker_container:
    name: agama-{{ item }}
    image: agama
    volumes: /opt/agama:/opt/agama
    env:
      AGAMA_DATABASE_URI=mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{mysql_database}}
    ports: "{{ agama_port + item }}:8000"
    state: started
    restart_policy: always
  loop: "{{ range(0, container_number) | list }}"
  no_log: true

- name: Assign cnames
  include_role:
    name: "cname"
  vars:
    service: "www{{inventory_hostname | replace('davidayson8','')}}"
  
  