- name: Make Agama Directory 
  ansible.builtin.file:
    path: /opt/agama
    state: directory

- name: Install agama application
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama/agama.py
  
- name: Download docker agama
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
    dest: /opt/agama/Dockerfile

- name: Build Docker Image
  community.docker.docker_image:
  name: agama
  source: build
  build:
    path: /opt/agama

- name: Create Data Container 
  community.docker.docker_container:
    name: agama
    image: agama
    state: present
    volumes: /opt/agama:/opt/agama
    env: 
      AGAMA_DATABASE_URI=mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{mysql_database}}
    ports: "{{ agama_port }}:8000"
    state: started
    restart_policy: always
  no_log: true