- name: Create agama user
  ansible.builtin.user:
    name: agama
    state: present
    system: yes

- name: Create /opt/agama directory
  ansible.builtin.file:
    path: /opt/agama
    state: directory
    owner: agama
    group: agama

- name: Install AGAMA dependencies
  ansible.builtin.apt:
    name:
      - python3
      - python3-venv
      - sqlite3
    state: present
    update_cache: no

- name: Download AGAMA application
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/hudolejev/agama/master/agama.py"
    dest: /opt/agama/agama.tar.gz
    owner: agama
    group: agama
