- name: Install dependency for nsupdate
  ansible.builtin.apt:
    name: python3-dnspython
    state: present

- name: Add cname record for DNS servers
  community.general.nsupdate:
    key_algorithm: "hmac-sha256"
    key_name: "nsupdatekey"
    key_secret: "{{ nsupdatekey_password }}"
    record: "{{ service }}"
    server: "{{ hostvars[groups['dns_primary'][0]]['ansible_default_ipv4']['address'] }}"
    state: present
    type: CNAME
    zone: "{{ domain_name }}"
    value: "{{ inventory_hostname }}"