- name: Restart Rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
    enabled: true

- name: Restart Bind9
  ansible.builtin.service:
    name: bind9
    state: restarted
    enabled: true