- name: Install MySQL server
  ansible.builtin.apt:
    name: mysql-server
    state: present

- name: Ensure MySQL is running and enabled
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes


