- name: Install MySQL server
  ansible.builtin.apt:
    name: mysql-server
    state: present

- name: Install Python MySQL client
  ansible.builtin.apt:
    name: python3-pymysql
    state: present
  become: true

- name: Add MySQL bind address override
  ansible.builtin.template:
    src: override.cnf.j2
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Restart MySQL
      
- name: Ensure MySQL is running and enabled
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"

- name: Create cnf template
  ansible.builtin.template:
    src: .my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
    owner: prometheus
    group: prometheus
  notify: Restart MySQL exporter

- name: Install MySQL exporter
  ansible.builtin.apt:
    name: prometheus-mysqld-exporter
    state: present

- name: MySQL exporter user
  community.mysql.mysql_user:
    name: " {{ exporter_user }}"
    password: "{{ exporter_password }}"
    priv: "*.*:PROCESS,REPLICATION CLIENT, SELECT"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify: Restart MySQL exporter  

- name: Ensure mysql exporter running and enabled
  ansible.builtin.service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: true