- name: Install MySQL server
  ansible.builtin.apt:
    name: mysql-server
    state: present

- name: Install Python MySQL client
  ansible.builtin.apt:
    name: python3-pymysql
    state: present
  become: true

- name: Add MySQL bind address override
  ansible.builtin.copy:
    dest: /etc/mysql/mysql.conf.d/override.cnf
    content: |
      [mysqld]
      bind-address = 0.0.0.0
  notify: Restart MySQL
  
- name: Restart MySQL
  ansible.builtin.service:
    name: mysql
    state: restarted
    
- name: Ensure MySQL is running and enabled
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"


