- name: Restart InfluxDB
  ansible.builtin.service:
    name: influxdb
    state: restarted

- name: Restart Telegraf
  ansible.builtin.service:
    name: telegraf
    state: restarted

- name: Restart Systemctl
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart cron
  ansible.builtin.service:
    name: cron
    state: restarted
    