- name: Install Bind9
  ansible.builtin.apt:
    name: 
      - bind9
      - prometheus-bind-exporter
    state: present

- name: Ensure Bind9 service is started and running
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - named
    - prometheus-bind-exporter

- name: Configure named.conf files Template
  ansible.builtin.template:
    src: named.conf.{{ item }}.j2
    dest: /etc/bind/named.conf.{{ item }}
    mode: '0644'
  with_items:
    - options
    - local
  notify: 
    - Reload Bind9
    - Restart Exporter

- name: Run Zone template
  ansible.builtin.template:
    src: zone.j2
    dest: /var/cache/bind/db.{{ domain_name }}
  notify: Restart Bind9

