- name: Install Bind9
  ansible.builtin.apt:
    name: 
      - bind9
    state: present

- name: Configure named.conf files Template
  ansible.builtin.template:
    src: named.conf.{{ item }}.j2
    dest: /etc/bind/named.conf.{{ item }}
    mode: '0644'
  with_items:
    - options
    - local
  notify: 
    - Restart Bind9
    - Reload systemd
  no_log: true

- name: Run Zone template
  ansible.builtin.template:
    src: zone.j2
    dest: /var/cache/bind/db.{{ domain_name }}
    mode: '0644'
    force: no
  no_log: true
  notify: Reload Bind9

- name: Run Reverse Zone template
  ansible.builtin.template:
    src: rev.zone.j2
    dest: /var/cache/bind/rev.db.{{ domain_name }}
    force: yes
    mode: '0644'
  when: inventory_hostname in groups['dns_primary']
  no_log: true
  notify: Reload Bind9

- name: Install dependency for nsupdate
  ansible.builtin.apt:
    name: python3-dnspython
    state: present

- name: Execute handlers
  ansible.builtin.meta: flush_handlers

- name: Add backup record on backup DNS servers
  community.general.nsupdate:
    key_algorithm: "hmac-sha256"
    key_name: "nsupdatekey"
    key_secret: "{{ nsupdatekey_password }}"
    record: "{{ backup_user }}"
    server: "{{ hostvars[groups['dns_primary'][0]]['ansible_default_ipv4']['address'] }}"
    state: present
    type: A
    zone: "{{ domain_name }}"
    value: "{{ backup_server }}"
  run_once: True
  when: inventory_hostname in groups['dns_primary']
  no_log: true

- name: Ensure Bind9 service is started and running
  ansible.builtin.systemd:
    name: bind9
    state: started
    enabled: yes

- name: Create bind_exporter user
  ansible.builtin.user:
    name: bind_exporter
    system: yes
    shell: /usr/sbin/nologin

- name: Download Bind9 exporter
  ansible.builtin.get_url:
    url: https://github.com/prometheus-community/bind_exporter/releases/download/v0.7.0/bind_exporter-0.7.0.linux-amd64.tar.gz
    dest: /opt/bind_exporter.tar.gz

- name: Create directory for Bind Exporter
  ansible.builtin.file:
    path: /opt/bind_exporter
    state: directory
    mode: '0755'

- name: Extract Bind9 exporter
  ansible.builtin.unarchive:
    src: /opt/bind_exporter.tar.gz
    dest: /opt/bind_exporter
    extra_opts: [--strip-components=1]
    remote_src: yes

- name: Create a symlink for the Bind Exporter executable
  ansible.builtin.file:
    src: /opt/bind_exporter/bind_exporter
    dest: /usr/local/bin/prometheus-bind-exporter
    state: link
    mode: '0755'

- name: Create Bind9 exporter systemd service
  ansible.builtin.template:
    src: bind_exporter.service
    dest: /etc/systemd/system/prometheus-bind-exporter.service
  notify:
    - Reload systemd
    - Restart Exporter

- name: Ensure Bind9 exporter service is started and running
  ansible.builtin.systemd:
    name: prometheus-bind-exporter
    state: started
    enabled: yes

- name: Assign cnames
  include_role:
    name: "cname"
  vars:
    service: "ns{{inventory_hostname | replace('davidayson8','')}}"

  