- name: Install Bind9
  ansible.builtin.apt:
    name: bind9
    state: present

- name: Configure named.conf files Template
  ansible.builtin.template:
    src: named.conf.{{ item }}.j2
    dest: /etc/bind/named.conf.{{ item }}
    mode: '0644'
  with_items:
    - options
    - local
  notify: Reload Bind9

- name: Run Zone template
  ansible.builtin.template:
    src: zone.j2
    dest: /var/cache/bind/db.{domain_name}
  notify: Restart Bind9

- name: Ensure Bind9 service is started and running
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: yes

- name: Reload Bind9  
  ansible.builtin.service:
    name: bind9
    state: reloaded

- name: Restart Bind9
  ansible.builtin.service:
    name: bind9
    state: restarted
