- name: Install Bind9
  ansible.builtin.apt:
    name: 
      - bind9
    state: present

- name: Download Bind9 exporter
  ansible.builtin.get_url:
    url: https://github.com/prometheus-community/bind_exporter/releases/download/v0.7.0/bind_exporter-0.7.0.linux-amd64.tar.gz
    dest: /opt/bind_exporter.tar.gz

- name: Create directory for Bind Exporter
  ansible.builtin.file:
    path: /opt/bind_exporter
    state: directory
    mode: '0755'

- name: Extract Bind9 exporter
  ansible.builtin.unarchive:
    src: /opt/bind_exporter.tar.gz
    dest: /opt/bind_exporter
    extra_opts: [--strip-components=1]
    remote_src: yes

- name: Create a symlink for the Bind Exporter executable
  ansible.builtin.file:
    src: /opt/bind_exporter/bind_exporter
    dest: /usr/local/bin/prometheus-bind-exporter
    state: link
    mode: '0755'

- name: Create Bind9 exporter systemd service
  ansible.builtin.template:
    src: bind_exporter.service
    dest: /etc/systemd/system/prometheus-bind-exporter.service
  notify:
    - Reload systemd
    - Restart Exporter

- name: Ensure Bind9 exporter service is started and running
  ansible.builtin.systemd:
    name: prometheus-bind-exporter
    state: started
    enabled: yes

- name: Ensure Bind9 service is started and running
  ansible.builtin.systemd:
    name: bind9
    state: started
    enabled: yes

- name: Configure named.conf files Template
  ansible.builtin.template:
    src: named.conf.{{ item }}.j2
    dest: /etc/bind/named.conf.{{ item }}
    mode: '0644'
  with_items:
    - options
    - local
  notify: 
    - Restart Bind9
    - Reload systemd
    - Restart Exporter

- name: Run Zone template
  ansible.builtin.template:
    src: zone.j2
    dest: /var/cache/bind/db.{{ domain_name }}
  notify: Restart Bind9

- name: Add DNS record for backup server
  ansible.builtin.lineinfile:
    path: /var/cache/bind/db.{{ domain_name }}
    line: "backup IN A {{ backup_server }}"
    create: yes
  notify: Restart Bind9
