#- name: Ansible ping module
#  ansible.builtin.ping:
---
#- name: Create user juri
#  ansible.builtin.user:
#    name: juri
#    state: present
#    shell: /bin/bash

#- name: Create user roman
#  ansible.builtin.user:
#    name: roman
#    state: present
#    shell: /bin/bash

#- name: Set authorized keys taken from url for juri
#  ansible.posix.authorized_key:
#    user: juri
#    key: https://github.com/hudolejev.keys

#- name: Set authorized keys taken from url for roman
#  ansible.posix.authorized_key:
#    user: roman
#    key:  https://github.com/romankuchin.keys
    
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Install Prometheus node 
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present

- name: Run Rsyslog template
  ansible.builtin.template:
    src: rsyslog.conf
    dest: /etc/rsyslog.d/prometheus.conf
    mode: '0644'
  notify: Restart Rsyslog

- name: Create backup user
  ansible.builtin.user:
    name: backup
    state: present
    home: /home/backup
    shell: /bin/bash
    generate_ssh_key: true
    ssh_key_file: /home/backup/.ssh/id_rsa
  
- name: Ensure .ssh directory exists for backup user
  ansible.builtin.file:
    path: /home/backup/.ssh
    state: directory
    owner: backup
    group: backup
    mode: '0700'

- name: Add backup server key to known_hosts for backup user
  ansible.builtin.template:
    src: known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup
    mode: '0644'
